### ISSUE TITLE
什么开源协议？

### ISSUE THREAD

**Issue by weathon** [PanJiaChen/Music-Visualization#1]
这个项目太棒了！请问是什么开源协议？我可以拿去用吗？@PanJiaChen

**Comment by PanJiaChen** [comment]
已增加了 MIT 协议。

不过要补充一点，这个项目已经是远古时期代码了，代码质量什么的都不能保证，也暂时不会维护和迭代了。

**Comment by weathon** [comment]
没问题，我只是写个小程序
